@startuml

title OpenID Provider App to Relying Party

box "Relying Party" #LightBlue
participant "Relying Party Backend" as rpb
participant "Relying Party Website" as rpw
participant "Relying Party App" as rpa
end box
participant "OS" as os
box "OpenID Provider" #LightGreen
participant "OpenID Provider App" as opa
participant "OpenID Provider Website" as opw
participant "Authorization Server" as as
end box

alt callingActivity?.packageName != null
   rpw <- opa: GET /.well-known/assetlinks.json
   rpw --> opa: return (packageName, baseCertFingerprint)
   os <- opa: getCertificate(callingActivity?.packageName)
   os --> opa: return (foundCertFingerprint)
   opa -> opa: verify foundCertFingerprint
   os <<- opa: setResult(intent)
   rpa <<- os: setResult(intent)
else
   os <- opa: getDefaultBrowserPackageName()
   os --> opa: return (browserPackageName, cert_fingerprint)
   opa -> opa: verify cert_fingerprint
   os <<- opa: Intent(URL).setPackage(browserPackageName)
   rpw <<- os: Intent(URL).setPackage(browserPackageName)
end

@enduml
