@startuml

title OpenID Provider Web to Relying Party

box "Relying Party" #LightBlue
participant "Relying Party Backend" as rpb
participant "Relying Party Website" as rpw
participant "Relying Party App" as rpa
end box
participant "OS" as os
box "OpenID Provider" #LightGreen
participant "OpenID Provider App" as opa
participant "OpenID Provider Website" as opw
participant "Authorization Server" as as
end box

opw <- as: Authorization Response (code)
rpb <- opw: Authorization Response (code)
rpb -> rpb: change url to intent:// scheme
rpb -> os: intent://...?code=...#Intent;scheme=https;package=...;end
rpa <- os: Intent(URL).setPackage(...)

@enduml
